/**
 * This code was generated by Builder.io.
 */
import React, {useState,useEffect} from "react";
import styles from "./FooterLinks.module.css";
import { fetchFooterLinks } from "@/components/api/footerLinksApi";

const FooterLinks = () => {
const [footerLinks, setFooterLinks] = useState([]);

  useEffect(() => {
    const getFooterLinks = async () => {
      try {
        const data = await fetchFooterLinks();
        setFooterLinks(data);
      } catch (error) {
        console.error("Error fetching notifications:", error);
      }
    };
    getFooterLinks();
  }, []);

  return (
    <footer className={styles.footer}>
      {footerLinks.map((link, index) => (
        <div key={index} className={styles.linkContainer}>
          {index > 0 && <div className={styles.separator}>｜</div>}
          <a href="#" className={styles.footerLink}>
            {link.text}
          </a>
        </div>
      ))}
    </footer>
  );
};

export default FooterLinks;
