/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const LoginButton = ({ formID, submitLink, nl }) => {
  return (
    <StyledLoginForm id={formID} action={submitLink} method="post">
      <input type="hidden" name="nl" value={nl} />
      <StyledLoginButton type="submit">mopitaにログイン</StyledLoginButton>
    </StyledLoginForm>
  );
};

const StyledLoginForm = styled.form`
  width: 100%;
`;

const StyledLoginButton = styled.button`
  border-radius: 4px;
  background-color: rgba(102, 181, 116, 1);
  align-self: center;
  margin-top: 4px;
  width: 100%;
  padding: 8px 46px;
  color: white;
  border: none;
  cursor: pointer;
  @media (max-width: 991px) {
    padding: 0 20px;
  }
`;

export default LoginButton;
