/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import TermsAgreement from "./TermsAgreement";
import LoginInstructions from "./LoginInstructions";
import SubscriptionOptions from "./SubscriptionOptions";
import TermsAndConditions from "./TermsAndConditions";
import LoginForm from "../../LoginForm/LoginForm";

const PurchaseContainer = () => {

  return (
    <StyledPurchaseContainer>
      <TermsAgreement />
      <LoginInstructions />
      <SubscriptionOptions />
      <LoginForm />
      <TermsAndConditions />
    </StyledPurchaseContainer>
  );
};

const StyledPurchaseContainer = styled.main`
  border-radius: 2px;
  display: flex;
  flex-direction: column;
  align-items: center;
  color: rgba(74, 74, 74, 1);
  font: 400 14px/1 Abel, sans-serif;
  text-align: center;
`;

export default PurchaseContainer;
