/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LoginForm.module.css";

const LoginForm = ( {data} ) => {
  const handleSubmit = () => {
    console.log('login to mopita')
  };

  return (
    <form
      id={data.formId}
      method="post"
      action={data.submitLink}
      className={styles.loginForm}
    >
      <button type="submit" className={styles.loginButton}>
        mopitaにログイン
      </button>
      <input type="hidden" name="nl" value={data.nl}/>
    </form>
  );
};

export default LoginForm;
