/**
 * This code was generated by Builder.io.
 */
import React, {useState,useEffect} from "react";
import styles from "./LoginForm.module.css";
import { fetchLoginData } from "../api/queryApi";

const LoginForm = () => {
  const [loginData,setLoginData] = useState([]);

  useEffect(() => {
    const getLoginData = async () => {
      try {
        const response = await fetchLoginData();
        setLoginData(response.data);
      } catch (error) {
        console.log("Error fetching subscripton data:", error);
      }
    }
    getLoginData();
  }, []);

  return (
    <>
      {loginData.map((data, index) => (
        <form
          key={index}
          id={data.formId}
          method="post"
          action={data.submitlink}
          className={styles.loginForm}
        >
          <button type="submit" className={styles.loginButton}>
            mopitaにログイン
          </button>
          <input type="hidden" name="nl" value={data.nl}/>
        </form>
      ))}
    </>
    // <form
    //   id={data.formId}
    //   method="post"
    //   action={data.submitlink}
    //   className={styles.loginForm}
    // >
    //   <button type="submit" className={styles.loginButton}>
    //     mopitaにログイン
    //   </button>
    //   <input type="hidden" name="nl" value={data.nl}/>
    // </form>
  );
};

export default LoginForm;
