/**
 * This code was generated by Builder.io.
 */
import React,{useState,useEffect} from 'react';
import styles from './Footer.module.css';
import FooterLinks from './FooterLinks';
import { fetchFooterTexts } from '../../api/queryApi';

const Footer = () => {
const [footerTexts, setFooterTexts] = useState([]);

  useEffect(() => {
    const getFooterTexts = async () => {
      try {
        const data = await fetchFooterTexts();
        setFooterTexts(data.data);
      } catch (error) {
        console.error("Error fetching notifications:", error);
      }
    };
    getFooterTexts();
  }, []);
  
  return (
    <>
      <FooterLinks/>
      <footer className={styles.footer}>
        {footerTexts.map((item, index) => (
          <p key={index} className={styles.copyrightText}>{item.text}</p>
        ))}
      </footer>
    </>

  );
};

export default Footer;