/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const LoginInstructions = () => {
  return (
    <StyledLoginInstructions>
      すでにAdGuardを購入済みの方は、下記の「mopitaにログイン」よりログインを行ってください。
    </StyledLoginInstructions>
  );
};

const StyledLoginInstructions = styled.p`
  margin: 12px 0 15px 29px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

export default LoginInstructions;
