/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const subscriptionData = [
  {
    formID: "form1",
    submitLink: "/submit1",
    countNumber: 1,
    countUnit: "台",
    price: 220,
    ci: "ci1",
    act: "act1",
    nl: "nl1",
    cl: "cl1",
    fl: "fl1",
  },
  {
    formID: "form2",
    submitLink: "/submit2",
    countNumber: 3,
    countUnit: "台",
    price: 330,
    ci: "ci2",
    act: "act2",
    nl: "nl2",
    cl: "cl2",
    fl: "fl2",
  },
  {
    formID: "form3",
    submitLink: "/submit3",
    countNumber: 5,
    countUnit: "台",
    price: 550,
    ci: "ci3",
    act: "act3",
    nl: "nl3",
    cl: "cl3",
    fl: "fl3",
  },
];

const SubscriptionOptions = () => {
  return (
    <StyledSubscriptionOptions>
      {subscriptionData.map((option, index) => (
        <SubscriptionOption key={index} option={option} />
      ))}
    </StyledSubscriptionOptions>
  );
};

const SubscriptionOption = ({ option }) => {
  const {
    formID,
    submitLink,
    countNumber,
    countUnit,
    price,
    ci,
    act,
    nl,
    cl,
    fl,
  } = option;

  return (
    <StyledOption>
      <form id={formID} action={submitLink} method="post">
        <input type="hidden" name="ci" value={ci} />
        <input type="hidden" name="act" value={act} />
        <input type="hidden" name="nl" value={nl} />
        <input type="hidden" name="cl" value={cl} />
        <input type="hidden" name="fl" value={fl} />
        <DeviceCount>
          <span>モバイル/PC 合計 </span>
          <DeviceNumber>{countNumber}</DeviceNumber>
          <span>{countUnit}</span>
        </DeviceCount>
        <div>月額利用登録 {price}円 (税込)</div>
        <SubmitButton type="submit">登録する</SubmitButton>
      </form>
    </StyledOption>
  );
};

const StyledSubscriptionOptions = styled.section`
  display: flex;
  margin-top: 32px;
  width: 225px;
  max-width: 100%;
  flex-direction: column;
  font-size: 11px;
  color: rgba(255, 255, 255, 1);
  text-align: center;
  justify-content: center;
`;

const StyledOption = styled.div`
  border-radius: 4px;
  background-color: rgba(102, 181, 116, 1);
  display: flex;
  width: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: start;
  padding: 8px 46px;
  border: 1px solid rgba(102, 181, 116, 1);
  margin-top: 4px;
  @media (max-width: 991px) {
    padding: 0 20px;
  }
`;

const DeviceCount = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
`;

const DeviceNumber = styled.span`
  font-size: 28px;
  line-height: 0.8;
  align-self: stretch;
  width: 16px;
  margin: auto 0;
`;

const SubmitButton = styled.button`
  background-color: white;
  color: rgba(102, 181, 116, 1);
  border: none;
  border-radius: 4px;
  padding: 5px 10px;
  margin-top: 10px;
  cursor: pointer;
`;

export default SubscriptionOptions;
