/**
 * This code was generated by Builder.io.
 */
import React, { useEffect, useState } from "react";
import styled from "styled-components";
import DeviceSubscription from "../DeviceSubscription/DeviceSubscription";
import { fetchSubscriptionData } from "../api/queryApi";

// const [subscriptionData, setSubscriptionData] = useState(null);



// const subscriptionData = [
//   {
//     formID: "form1",
//     submitLink: "/submit1",
//     countNumber: 1,
//     countUnit: "台",
//     price: 220,
//     ci: "ci1",
//     act: "act1",
//     nl: "nl1",
//     cl: "cl1",
//     fl: "fl1",
//   },
//   {
//     formID: "form2",
//     submitLink: "/submit2",
//     countNumber: 3,
//     countUnit: "台",
//     price: 330,
//     ci: "ci2",
//     act: "act2",
//     nl: "nl2",
//     cl: "cl2",
//     fl: "fl2",
//   },
//   {
//     formID: "form3",
//     submitLink: "/submit3",
//     countNumber: 5,
//     countUnit: "台",
//     price: 550,
//     ci: "ci3",
//     act: "act3",
//     nl: "nl3",
//     cl: "cl3",
//     fl: "fl3",
//   },
// ];

const SubscriptionOptions = () => {
  const [subscriptionData, setSubscriptionData] = useState([]);

  useEffect(() => {
    const getSubscriptionData = async () => {
      try {
        const response = await fetchSubscriptionData();
        setSubscriptionData(response.data);
      } catch (error) {
        console.log("Error fetching subscripton data:", error);
      }
    }
    getSubscriptionData();
  }, []);

  return (
    <StyledSubscriptionOptions>
      {subscriptionData.map((option, index) => (
        <DeviceSubscription key={index} data={option} />
      ))}
    </StyledSubscriptionOptions>
  );
};


const StyledSubscriptionOptions = styled.section`
  display: flex;
  margin-top: 32px;
  width: 225px;
  max-width: 100%;
  flex-direction: column;
  font-size: 11px;
  color: rgba(255, 255, 255, 1);
  text-align: center;
  justify-content: center;
`;

const StyledOption = styled.div`
  border-radius: 4px;
  background-color: rgba(102, 181, 116, 1);
  display: flex;
  width: 100%;
  flex-direction: column;
  align-items: center;
  justify-content: start;
  padding: 8px 46px;
  border: 1px solid rgba(102, 181, 116, 1);
  margin-top: 4px;
  @media (max-width: 991px) {
    padding: 0 20px;
  }
`;

const DeviceCount = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
`;

const DeviceNumber = styled.span`
  font-size: 28px;
  line-height: 0.8;
  align-self: stretch;
  width: 16px;
  margin: auto 0;
`;

const SubmitButton = styled.button`
  background-color: white;
  color: rgba(102, 181, 116, 1);
  border: none;
  border-radius: 4px;
  padding: 5px 10px;
  margin-top: 10px;
  cursor: pointer;
`;

export default SubscriptionOptions;
