/**
 * This code was generated by Builder.io.
 */
"use client";
import React, { useState, useEffect } from "react";
import styled from "styled-components";
import { fetchTermsLinks } from "../api/queryApi";

const TermsAgreement = () => {
  const [termsLink1, setTermsLink1] = useState([]);
  const [termsLink2, setTermsLink2] = useState([]);

  useEffect(() => {
    const getlinks = async () => {
      try{
        const data = await fetchTermsLinks();
        setTermsLink1(data.data[0]);
        setTermsLink2(data.data[1]);
      } catch(error){
        console.log("error:", error);
      }
    };
    getlinks();
  }, []);

  return (
    <StyledTermsAgreement>
      <span>ご利用をご希望の方は、</span>
      <TermsLink href={termsLink1.link}>{termsLink1.text}</TermsLink>
      <span>および</span>
      <TermsLink href={termsLink2.link}>{termsLink2.text}</TermsLink>
      <span>に同意して下記の「月額利用登録」より課金登録 (入会) を</span>
      <span>行ってください。</span>
      <span>登録完了後、即時ご利用いただけます。</span>
    </StyledTermsAgreement>
  );
}; 

const StyledTermsAgreement = styled.section`
  align-self: stretch;
  display: flex;
  gap: 5px;
  flex-wrap: wrap;
  margin-left: 100px;
  margin-bottom: 15px;
`; 

const TermsLink = styled.a`
  color: #66b574;
  cursor: pointer;
`;

export default TermsAgreement;
