/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

const TermsAndConditions = () => {
  return (
    <StyledTermsAndConditions>
      <Paragraph>
        ・
        本サービスは、mopitaの会員ログイン・課金決済機能を利用しています。お支払いに関しては、mopitaが対応してい
        <br />
        る決済方法、mopitaアカウントに登録されている支払い方法に準じます。
      </Paragraph>
      <Paragraph>
        ・
        本サービスは登録完了後から、解約まで1ヶ月ごとの自動契約更新となり、毎月月額料金がかかります。月の途中で本
        <br />
        サービスを申し込んだ場合や解約した場合でも、月額料金満額をお支払いいただきます。
      </Paragraph>
      <Paragraph>
        ・ 解約手続きはサイト下部の会員解除より行ってください。
      </Paragraph>
    </StyledTermsAndConditions>
  );
};

const StyledTermsAndConditions = styled.section`
  margin-top: 38px;
`;

const Paragraph = styled.p`
  line-height: 20px;
  text-align: center;
  margin: 17px 0 0 10px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

export default TermsAndConditions;
