/**
 * This code was generated by Builder.io.
 */
import React, { useState, useEffect } from "react";
import styled from "styled-components";

const TermsAgreement = () => {
  const [termsLink1, setTermsLink1] = useState("");
  const [termsLink2, setTermsLink2] = useState("");

  useEffect(() => {
    setTermsLink1("/terms1");
    setTermsLink2("/terms2");
  }, []);

  return (
    <StyledTermsAgreement>
      <span>ご利用をご希望の方は、</span>
      <TermsLink href={termsLink1}>販売規約</TermsLink>
      <span>および</span>
      <TermsLink href={termsLink2}>AdGuardの利用規約</TermsLink>
      <span>に同意して下記の「月額利用登録」より課金登録 (入会) を</span>
      <span>行ってください。</span>
      <span>登録完了後、即時ご利用いただけます。</span>
    </StyledTermsAgreement>
  );
};

const StyledTermsAgreement = styled.section`
  align-self: stretch;
  display: flex;
  gap: 5px;
  flex-wrap: wrap;
`;

const TermsLink = styled.a`
  color: rgba(102, 181, 116, 1);
  cursor: pointer;
`;

export default TermsAgreement;
