/**
 * This code was generated by Builder.io.
 */
import React, {useState,useEffect} from "react";
import AdGuardHeader from "./AdGuardHeader";
import NotificationBanner from "./NotificationBanner";
import FeatureSection from "./FeatureSection";
import styles from "./AdGuardStyles.module.css";
import { fetchNotifications } from "../api/queryApi";
import { fetchAnnouncements } from "../api/queryApi";
import AnnounceBanner from "./AnnounceBanner";

const AdGuardMain = () => {
  const [notifications, setNotifications] = useState([]);
  const [announcements, setAnnouncements] = useState([]);

  useEffect(() => {
    const getNotifications = async () => {
      try {
        const data = await fetchNotifications();
        setNotifications(data.data);
      } catch (error) {
        console.error("Error fetching notifications:", error);
      }
    };
    getNotifications();
  }, []);

  useEffect(() => {
    const getAnnouncements = async () => {
      try{
        const data = await fetchAnnouncements();
        setAnnouncements(data.data);
      }catch(error) {
        console.error("Error fetching announcements:", error);
      }
    };
    getAnnouncements();
  }, []);

  return (
    <main className={styles.mainContainer}>
      <AdGuardHeader />
      {notifications.map((notification, index) => (
        <NotificationBanner
          key={index}
          text={notification.text}
          href={notification.link}
        />
      ))}
      {announcements.map((announcement, index) => (
        <AnnounceBanner 
          key={index}
          {...announcement}          
        />
      ))}
      <FeatureSection />
      <footer className={styles.footer}>
        <a href="#purchase" className={styles.footerLink}>
          AdGuardの購入 または mopitaへのログイン
        </a>
      </footer>
    </main>
  );
};

export default AdGuardMain;
