/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./AdGuardStyles.module.css";

const AdGuardHeader = () => {
  return (
    <header className={styles.header}>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/63dfc536389dd0abed6eae0d20a885726fa0d958ea7400ce6c0ad4fcffda6fd4?apiKey=3808323d051d4dd3b06c5d8d2529646e&&apiKey=3808323d051d4dd3b06c5d8d2529646e"
        alt=""
        className={styles.backgroundImage}
      />
      <div className={styles.headerContent}>
        <img
          loading="lazy"
          src="https://cdn.builder.io/api/v1/image/assets/TEMP/8b513a0491d55c4f6955f68d79c47c9d84356c0c9bfd4493bdc0e2503732a47d?apiKey=3808323d051d4dd3b06c5d8d2529646e&&apiKey=3808323d051d4dd3b06c5d8d2529646e"
          alt="AdGuard Logo"
          className={styles.logo}
        />
        <h1 className={styles.title}>快適なウェブへ。</h1>
        <p className={styles.description}>
          AdGuardは、侵入型広告やオンライン追跡を取り除き、不正なソフトウェアからコンピュータを保護するための
          最良の方法です。AdGuardを使って速く安全で快適なインターネットをお楽しみください！
        </p>
      </div>
    </header>
  );
};

export default AdGuardHeader;
