/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./AdGuardStyles.module.css";

const NotificationBanner = ({ text, href }) => {
  return (
    <a href={href} className={styles.notificationBanner}>
      {text}
    </a>
  );
};

export default NotificationBanner;
