/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./AdGuardStyles.module.css";

const FeatureCard = ({ imageSrc, title, description }) => {
  return (
    <div className={styles.featureCard}>
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className={styles.featureIcon}
      />
      <h3 className={styles.featureTitle}>{title}</h3>
      <p className={styles.featureDescription}>{description}</p>
    </div>
  );
};

export default FeatureCard;
